---
apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: hello
  namespace: dp
spec:
  replicas: 1
  version: 10.0.4.0
  license:
    accept: true
    use: production
    license: L-RJON-C5SF54
  users:
  - name: admin
    accessLevel: privileged
    passwordSecret: admin-credentials
  domains:
  - name: hello
    dpApp:
      config:
      - default-cfg
      - hello-cfg
      local:
      - default-local
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: dp
spec:
  selector:
    app.kubernetes.io/component: datapower
    app.kubernetes.io/instance: dp-hello
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: mpgw
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-route
  namespace: dp
spec:
  host: hello.itzroks-664001s7x8-0phxra-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-east.containers.appdomain.cloud
  port:
    targetPort: 8000
  tls:
    termination: edge
  to:
    kind: Service
    name: hello-service
    weight: 100
  wildcardPolicy: None
---
